// Auto-generated wrapper entry for account
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/account.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
