// Auto-generated wrapper entry for cart
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/cart.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
