// Auto-generated wrapper entry for product
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/product.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
