// Auto-generated wrapper entry for quiz
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/quiz.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
