// Auto-generated wrapper entry for shop
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/shop.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
