// Auto-generated wrapper entry for subscription
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/subscription.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
