// Auto-generated wrapper entry for try-on
// This file is automatically generated by rspack.config.ts
import PageComponent from '../src/pages/try-on.tsx';
import { initPage } from '../src/core/page-entry';

initPage(PageComponent);
